name: build
on: [push]

jobs:
  all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: 'Install dependencies: zlib (Windows)'
        if: ${{ runner.os == 'Windows' }}
        run: |
          vcpkg install zlib:x64-windows
          $cmtc = "CMAKE_TC_ARG=-DCMAKE_TOOLCHAIN_FILE=" + $env:VCPKG_INSTALLATION_ROOT + "\scripts\buildsystems\vcpkg.cmake"
          echo $cmtc >> $env:GITHUB_ENV
      - name: 'Install test dependencies: nihtest'
        run: |
          pip install nihtest
      - name: Configure
        run: |
          cmake ${{env.CMAKE_TC_ARG}} -B ${{runner.workspace}}/build -S ${{github.workspace}}
      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --config Release
      - name: Run tests
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest -C Release --output-on-failure --timeout 99
